server:
  port: 8081
dubbo:
  application:
    name: bank-provider
    id: bank-provider
    protocol:
      name: dubbo
      port: 20800
      id: dubbo
  registry:
    address: zookeeper://127.0.0.1:2181